# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'utils/etc/Qt_design/Tab4_vis_config.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

from PyQt5 import QtCore, QtGui, QtWidgets
import os


class Ui_MLEMVisCfg (object):
    def setupUi (self, Visconfig):
        Visconfig.setObjectName("Visconfig")
        Visconfig.setGeometry(580, 380, 450, 236)  # setGeometry(x, y, w, h)
        
        self.groupBox = QtWidgets.QGroupBox(Visconfig)
        self.groupBox.setGeometry(QtCore.QRect(10, 10, 430, 215))
        self.groupBox.setObjectName("groupBox")
        self.formLayout = QtWidgets.QFormLayout(self.groupBox)
        self.formLayout.setObjectName("formLayout")
        
        # ====== Title ======
        self.label_ttl = QtWidgets.QLabel(self.groupBox)
        self.label_ttl.setAutoFillBackground(True)
        self.label_ttl.setScaledContents(False)
        self.label_ttl.setAlignment(QtCore.Qt.AlignCenter)
        self.label_ttl.setWordWrap(False)
        self.label_ttl.setOpenExternalLinks(False)
        self.label_ttl.setObjectName("label_ttl")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.SpanningRole, self.label_ttl)
        
        # ====== (1) MLEM DAT ======
        self.label_dat = QtWidgets.QLabel(self.groupBox)
        self.label_dat.setObjectName("label_dat")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_dat)
        
        self.comboBox_mlem = QtWidgets.QComboBox(self.groupBox)
        self.comboBox_mlem.setObjectName("comboBox_mlem")
        self.comboBox_mlem.setMinimumSize(120, 25)
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.comboBox_mlem)

        # - list of MLEM DAT files -
        self.list_mlem = os.listdir(f'data/recon/MLEM/OUTPUT/{self.comboBox_mlem.currentText()}')
        self.maxiters  = len(self.list_mlem)
        self.comboBox_mlem.addItems(self.list_mlem)
        self.comboBox_mlem.setCurrentIndex(0)
        
        # ====== (2) Iter ======
        self.label_iter = QtWidgets.QLabel(self.groupBox)
        self.label_iter.setObjectName("label_iter")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_iter)
        
        self.maxiters = len(self.list_mlem)
        self.spinBox_iter = QtWidgets.QSpinBox(self.groupBox)
        self.spinBox_iter.setObjectName("spinBox_iter")
        self.spinBox_iter.setProperty("value", self.maxiters)
        self.spinBox_iter.setSingleStep(1)
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.spinBox_iter)
        
        # - maxiters_onchanged -
        self.maxiters_onchanged()  # onchanged of mlem dat
        self.comboBox_mlem.currentTextChanged.connect(self.maxiters_onchanged)
        
        # ====== (3) Spacing ======
        self.label_sp = QtWidgets.QLabel(self.groupBox)
        self.label_sp.setObjectName("label_sp")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_sp)
        
        self.spinBox_sp = QtWidgets.QSpinBox(self.groupBox)
        self.spinBox_sp.setObjectName("spinBox_sp")
        self.spinBox_sp.setSingleStep(1)
        self.spinBox_sp.setMinimum(1)
        self.spinBox_sp.setMaximum(1000)
        self.spinBox_sp.setValue(256)  # if more than 100, set Max/Min first!
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.spinBox_sp)
        
        # ====== (4) Axis ======
        self.label_axis = QtWidgets.QLabel(self.groupBox)
        self.label_axis.setObjectName("label_axis")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_axis)
        
        self.comboBox_axis = QtWidgets.QComboBox(self.groupBox)
        self.comboBox_axis.setEditable(True)
        self.comboBox_axis.setPlaceholderText("")
        self.comboBox_axis.setObjectName("comboBox_axis")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.comboBox_axis)
        self.comboBox_axis.addItems(['X','Y','Z'])
        self.comboBox_axis.setCurrentIndex(0)
        
        # ====== (5) Slice ======
        self.label_slice = QtWidgets.QLabel(self.groupBox)
        self.label_slice.setObjectName("label_slice")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.label_slice)
        
        self.horizSlider_slice = QtWidgets.QSlider(self.groupBox)
        self.horizSlider_slice.setOrientation(QtCore.Qt.Horizontal)
        self.horizSlider_slice.setObjectName("horizSlider_slice")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.horizSlider_slice)

        #  --- onchange ---
        self.ax_onchanged()
        self.comboBox_axis.currentTextChanged.connect(self.ax_onchanged)
        self.spinBox_sp.valueChanged.connect(self.ax_onchanged)
        self.horizSlider_slice.valueChanged.connect(self.slider_onchanged)
        
        self.label_slice1 = QtWidgets.QLabel(self.groupBox)
        self.label_slice1.setObjectName("label_slice1")
        self.label_slice1.setAlignment(QtCore.Qt.AlignCenter)
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.SpanningRole, self.label_slice1)
        
        # ====== Ok|cancel ======
        self.buttonBox = QtWidgets.QDialogButtonBox(self.groupBox)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setCenterButtons(True)
        self.buttonBox.setObjectName("buttonBox")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.SpanningRole, self.buttonBox)

        self.retranslateUi(Visconfig)
        self.buttonBox.accepted.connect(Visconfig.accept)  # type: ignore
        self.buttonBox.rejected.connect(Visconfig.reject)  # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Visconfig)

    def retranslateUi (self, Visconfig):
        _translate = QtCore.QCoreApplication.translate
        Visconfig.setWindowTitle(_translate("Visconfig", "MLEM vis config"))
        self.label_ttl.setText(_translate("Visconfig", "Config of MLEM visualization"))
        self.label_dat.setText(_translate("Visconfig", "MLEM Dat"))
        self.label_iter.setText(_translate("Visconfig", "Iteration"))
        self.label_sp.setText(_translate("Visconfig", "Spacing (mm)"))
        self.label_axis.setText(_translate("Visconfig", "Axis"))
        self.label_slice.setText(_translate("Visconfig", "Slice"))
        self.label_slice1.setText(_translate("Visconfig", str(self.horizSlider_slice.value())))
    
    def maxiters_onchanged (self):
        self.mlem_dir = f'data/recon/MLEM/OUTPUT/{self.comboBox_mlem.currentText()}'  
        self.maxiters = len([f for f in os.listdir(self.mlem_dir) \
                        if f.endswith('.DAT') and os.path.isfile(os.path.join(self.mlem_dir, f))])
        self.spinBox_iter.setValue(self.maxiters)
        self.spinBox_iter.setMaximum(self.maxiters)
        self.spinBox_iter.setMinimum(1) if self.maxiters > 0 else self.spinBox_iter.setMinimum(0)

    def ax_onchanged (self):
        self.axis = self.comboBox_axis.currentText()
        self.nimgx = int(self.spinBox_sp.value() / 0.8)
        
        if self.axis == 'X':
            self.xlabel='Z'
            self.ylabel='Y'
            self.horizSlider_slice.setRange(1, self.nimgx)
            self.horizSlider_slice.setValue(self.nimgx // 2)
        elif self.axis == 'Y':
            self.xlabel='Z'
            self.ylabel='X'
            self.horizSlider_slice.setRange(1, self.nimgy)
            self.horizSlider_slice.setValue(self.nimgy // 2)
        elif self.axis == 'Z':
            self.xlabel='X'
            self.ylabel='Y'
            self.horizSlider_slice.setRange(1, self.nimgz)
            self.horizSlider_slice.setValue(self.nimgz // 2)
        
    def slider_onchanged (self):
        self.slice = self.horizSlider_slice.value()
        self.label_slice1.setText(str(self.slice))

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Visconfig = QtWidgets.QDialog()
    ui = Ui_MLEMVisCfg()
    ui.setupUi(Visconfig)
    Visconfig.show()
    sys.exit(app.exec_())