# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'utils/etc/Qt_design/Tab4_MLEM_config.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MLEMReconCfg (object):

    def setupUi (self, MLEMconfig):
        MLEMconfig.setObjectName("MLEMconfig")
        MLEMconfig.setGeometry(600, 400, 310, 180)
        
        self.layoutWidget = QtWidgets.QWidget(MLEMconfig)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 10, 280, 150))
        self.layoutWidget.setObjectName("layoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.layoutWidget)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        
        # ====== Title ======
        self.label_ttl = QtWidgets.QLabel(self.layoutWidget)
        self.label_ttl.setAutoFillBackground(True)
        self.label_ttl.setScaledContents(False)
        self.label_ttl.setAlignment(QtCore.Qt.AlignCenter)
        self.label_ttl.setWordWrap(False)
        self.label_ttl.setOpenExternalLinks(False)
        self.label_ttl.setObjectName("label_ttl")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.SpanningRole, self.label_ttl)
        
        # ====== (1) Iteration ======
        self.label_iter = QtWidgets.QLabel(self.layoutWidget)
        self.label_iter.setObjectName("label_iter")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_iter)
        
        self.spinBox_iter = QtWidgets.QSpinBox(self.layoutWidget)
        self.spinBox_iter.setMinimum(1)
        self.spinBox_iter.setMaximum(100)
        self.spinBox_iter.setSingleStep(1)
        self.spinBox_iter.setProperty("value", 10)
        self.spinBox_iter.setObjectName("spinBox_iter")
        self.spinBox_iter.setMinimumSize(120, 30)
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.spinBox_iter)
        
        # ====== (2) Spacing ======
        self.label_sp = QtWidgets.QLabel(self.layoutWidget)
        self.label_sp.setObjectName("label_sp")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_sp)
        
        self.lineEdit_sp = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEdit_sp.setObjectName("lineEdit_sp")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.lineEdit_sp)
        
        # ====== (3) vx ======
        self.label_vx = QtWidgets.QLabel(self.layoutWidget)
        self.label_vx.setObjectName("label_vx")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_vx)
        
        self.lineEdit_vx = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEdit_vx.setObjectName("lineEdit_vx")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.lineEdit_vx)
        
        # ====== (4) xplanes ======
        self.label_xp = QtWidgets.QLabel(self.layoutWidget)
        self.label_xp.setObjectName("label_xp")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_xp)
        
        self.spinBox_xp = QtWidgets.QSpinBox(self.layoutWidget)
        self.spinBox_xp.setMinimum(2)
        self.spinBox_xp.setMaximum(120)
        self.spinBox_xp.setSingleStep(2)
        self.spinBox_xp.setProperty("value", 4)
        self.spinBox_xp.setObjectName("spinBox_xp")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.spinBox_xp)
        
        # ====== Ok|cancel ======
        self.buttonBox = QtWidgets.QDialogButtonBox(self.layoutWidget)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setCenterButtons(True)
        self.buttonBox.setObjectName("buttonBox")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.SpanningRole, self.buttonBox)

        self.retranslateUi(MLEMconfig)
        self.buttonBox.accepted.connect(MLEMconfig.accept)  # type: ignore
        self.buttonBox.rejected.connect(MLEMconfig.reject)  # type: ignore
        QtCore.QMetaObject.connectSlotsByName(MLEMconfig)

    def retranslateUi (self, MLEMconfig):
        _translate = QtCore.QCoreApplication.translate
        MLEMconfig.setWindowTitle(_translate("MLEMconfig", "ML-EM config"))
        self.label_ttl.setText(_translate("MLEMconfig", "Config of ML-EM recon"))
        self.label_iter.setText(_translate("MLEMconfig", "Iterations"))
        self.label_sp.setText(_translate("MLEMconfig", "Spacing (mm)"))
        self.lineEdit_sp.setText(_translate("MLEMconfig", "256"))
        self.lineEdit_sp.setPlaceholderText(_translate("MLEMconfig", "Distance of 2 boards (mm)"))
        self.label_vx.setText(_translate("MLEMconfig", "vx (mm)"))
        self.lineEdit_vx.setText(_translate("MLEMconfig", "0.8"))
        self.lineEdit_vx.setPlaceholderText(_translate("MLEMconfig", "Voxel size of x (mm)"))
        self.label_xp.setText(_translate("MLEMconfig", "xplanes"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MLEMconfig = QtWidgets.QDialog()
    
    ui = Ui_MLEMReconCfg()
    ui.setupUi(MLEMconfig)

    MLEMconfig.show()
    sys.exit(app.exec_())