# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'utils/etc/Qt_design/Tab4_SRM_config.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_SRMGenCfg (object):
    def setupUi (self, SRMGenCfg):
        SRMGenCfg.setObjectName("SRMGenCfg")
        SRMGenCfg.setGeometry(600, 400, 400, 180)
        
        self.layoutWidget = QtWidgets.QWidget(SRMGenCfg)
        self.layoutWidget.setGeometry(QtCore.QRect(20, 20, 360, 160))
        self.layoutWidget.setObjectName("layoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.layoutWidget)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        
        # Title
        self.label_ttl = QtWidgets.QLabel(self.layoutWidget)
        self.label_ttl.setAlignment(QtCore.Qt.AlignCenter)
        self.label_ttl.setObjectName("label_ttl")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.SpanningRole, self.label_ttl)
        
        # Spacing
        self.label_sp = QtWidgets.QLabel(self.layoutWidget)
        self.label_sp.setObjectName("label_sp")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_sp)
        
        self.lineEdit_sp = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEdit_sp.setObjectName("lineEdit_sp")
        self.lineEdit_sp.setMinimumSize(60, 25)
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.lineEdit_sp)
        
        # vx
        self.label_vx = QtWidgets.QLabel(self.layoutWidget)
        self.label_vx.setObjectName("label_vx")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_vx)
        
        self.lineEdit_vx = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEdit_vx.setObjectName("lineEdit_vx")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.lineEdit_vx)
        
        # Xplanes
        self.label_xp = QtWidgets.QLabel(self.layoutWidget)
        self.label_xp.setObjectName("label_xp")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_xp)
        
        self.spinBox_xp = QtWidgets.QSpinBox(self.layoutWidget)
        self.spinBox_xp.setMinimum(2)
        self.spinBox_xp.setSingleStep(2)
        # self.spinBox_xp.setMaximum(120)
        # self.spinBox_xp.setProperty("value", 20)
        self.spinBox_xp.setStepType(QtWidgets.QAbstractSpinBox.AdaptiveDecimalStepType)
        self.spinBox_xp.setDisplayIntegerBase(10)
        self.spinBox_xp.setObjectName("spinBox_xp")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.spinBox_xp)
        
        # Ok|Cancel
        self.buttonBox = QtWidgets.QDialogButtonBox(self.layoutWidget)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setCenterButtons(True)
        self.buttonBox.setObjectName("buttonBox")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.SpanningRole, self.buttonBox)

        self.retranslateUi(SRMGenCfg)
        self.buttonBox.accepted.connect(SRMGenCfg.accept)  # type: ignore
        self.buttonBox.rejected.connect(SRMGenCfg.reject)  # type: ignore
        QtCore.QMetaObject.connectSlotsByName(SRMGenCfg)

    def retranslateUi (self, SRMGenCfg):
        _translate = QtCore.QCoreApplication.translate
        SRMGenCfg.setWindowTitle(_translate("SRMGenCfg", "SRM config"))
        self.label_ttl.setText(_translate("SRMGenCfg", "Config of SRM generation"))
        
        self.label_sp.setText(_translate("SRMGenCfg", "spacing (mm)"))
        self.lineEdit_sp.setText(_translate("SRMGenCfg", "60"))
        self.lineEdit_sp.setPlaceholderText(_translate("SRMGenCfg", "Distance of 2 boards (mm)"))
        
        self.label_vx.setText(_translate("SRMGenCfg", "vx (mm)"))
        self.lineEdit_vx.setText(_translate("SRMGenCfg", "0.8"))
        self.lineEdit_vx.setPlaceholderText(_translate("SRMGenCfg", "Voxel size of x (mm)"))
        
        self.label_xp.setText(_translate("SRMGenCfg", "xplanes"))
        
        self.xp_onchanged()  # set maximum of xplanes
        self.lineEdit_sp.textChanged.connect(self.xp_onchanged)
        self.lineEdit_vx.textChanged.connect(self.xp_onchanged)
    
    def xp_onchanged (self):
        self.max_xp = int(float(self.lineEdit_sp.text()) / float(self.lineEdit_vx.text()))
        self.spinBox_xp.setMaximum(self.max_xp)
        self.spinBox_xp.setProperty("value", self.max_xp)


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    SRMGenCfg = QtWidgets.QDialog()
    ui = Ui_SRMGenCfg()
    ui.setupUi(SRMGenCfg)
    SRMGenCfg.show()
    sys.exit(app.exec_())