# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'utils/etc/Qt_design/Tab4_MLEM_config.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

from PyQt5 import QtCore, QtGui, QtWidgets
import glob


class Ui_ThrAngReconCfg (object):
    def setupUi (self, thrangconfig):
        thrangconfig.setObjectName("thrangconfig")
        thrangconfig.setGeometry(520, 350, 570, 270)
        
        self.layoutWidget = QtWidgets.QGroupBox(thrangconfig)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 10, 550, 250))
        self.layoutWidget.setObjectName("layoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.layoutWidget)
        self.formLayout.setObjectName("formLayout")
        # self.formLayout.setContentsMargins(0, 0, 0, 0)
        
        # Title
        self.label_ttl = QtWidgets.QLabel(self.layoutWidget)
        self.label_ttl.setAutoFillBackground(True)
        self.label_ttl.setScaledContents(False)
        self.label_ttl.setAlignment(QtCore.Qt.AlignCenter)
        self.label_ttl.setWordWrap(False)
        self.label_ttl.setOpenExternalLinks(False)
        self.label_ttl.setObjectName("label_ttl")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.SpanningRole, self.label_ttl)
        
        # 3-angle input
        self.label_input = QtWidgets.QLabel(self.layoutWidget)
        self.label_input.setObjectName("label_input")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_input)
        
        self.comboBox_input = QtWidgets.QComboBox(self.layoutWidget)
        self.comboBox_input.setObjectName("comboBox_input")
        self.comboBox_input.setMinimumSize(120, 25)
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.comboBox_input)
        # list of 3-angle input folders
        self.list_3ang = glob.glob("data/bin/*.bin")
        self.comboBox_input.addItems(self.list_3ang)
        self.comboBox_input.setCurrentIndex(0)

        # Iteration
        self.label_iter = QtWidgets.QLabel(self.layoutWidget)
        self.label_iter.setObjectName("label_iter")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_iter)
        
        self.spinBox_iter = QtWidgets.QSpinBox(self.layoutWidget)
        self.spinBox_iter.setMinimum(1)
        self.spinBox_iter.setMaximum(1000)
        self.spinBox_iter.setSingleStep(1)
        self.spinBox_iter.setProperty("value", 10)
        self.spinBox_iter.setObjectName("spinBox_iter")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.spinBox_iter)
        
        # Spacing
        self.label_sp = QtWidgets.QLabel(self.layoutWidget)
        self.label_sp.setObjectName("label_sp")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_sp)
        
        self.lineEdit_sp = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEdit_sp.setObjectName("lineEdit_sp")
        self.lineEdit_sp.setText("256")
        self.lineEdit_sp.textChanged.connect(self.xp_onchanged)
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.lineEdit_sp)
        
        # vx
        self.label_vx = QtWidgets.QLabel(self.layoutWidget)
        self.label_vx.setObjectName("label_vx")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_vx)
        
        self.lineEdit_vx = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEdit_vx.setObjectName("lineEdit_vx")
        self.lineEdit_vx.setText("0.8")
        self.lineEdit_vx.textChanged.connect(self.xp_onchanged)
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.lineEdit_vx)
        
        # Xplanes
        self.label_xp = QtWidgets.QLabel(self.layoutWidget)
        self.label_xp.setObjectName("label_xp")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.label_xp)
        
        self.spinBox_xp = QtWidgets.QSpinBox(self.layoutWidget)
        self.spinBox_xp.setMinimum(2)
        self.spinBox_xp.setSingleStep(2)
        self.spinBox_xp.setObjectName("spinBox_xp")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.spinBox_xp)
        
        self.xp_onchanged()  # set maximum of xplanes
        
        # Ok|Cancel
        self.buttonBox = QtWidgets.QDialogButtonBox(self.layoutWidget)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setCenterButtons(True)
        self.buttonBox.setObjectName("buttonBox")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.SpanningRole, self.buttonBox)

        self.retranslateUi(thrangconfig)
        self.buttonBox.accepted.connect(thrangconfig.accept)  # type: ignore
        self.buttonBox.rejected.connect(thrangconfig.reject)  # type: ignore
        QtCore.QMetaObject.connectSlotsByName(thrangconfig)

    def retranslateUi (self, thrangconfig):
        _translate = QtCore.QCoreApplication.translate
        thrangconfig.setWindowTitle(_translate("thrangconfig", "3-angle recon config"))
        self.label_ttl.setText(_translate("thrangconfig", "Config of 3-angle recon"))
        self.label_input.setText(_translate("thrangconfig", "3-angle source"))
        
        self.label_iter.setText(_translate("thrangconfig", "iterations"))
        
        self.label_sp.setText(_translate("thrangconfig", "spacing (mm)"))
        # self.lineEdit_sp.setText(_translate("thrangconfig", "60"))
        self.lineEdit_sp.setPlaceholderText(_translate("thrangconfig", "Distance of 2 boards (mm)"))
        
        self.label_vx.setText(_translate("thrangconfig", "vx (mm)"))
        # self.lineEdit_vx.setText(_translate("thrangconfig", "0.5"))
        self.lineEdit_vx.setPlaceholderText(_translate("thrangconfig", "Voxel size of x (mm)"))
        
        self.label_xp.setText(_translate("thrangconfig", "xplanes"))
    
    def xp_onchanged (self):
        self.max_xp = int(float(self.lineEdit_sp.text())/float(self.lineEdit_vx.text()))
        self.spinBox_xp.setMaximum(self.max_xp)
        self.spinBox_xp.setProperty("value", self.max_xp)
        # print(f"max of xplane = {self.lineEdit_sp.text()} / {self.lineEdit_vx.text()} = {self.max_xp}")


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    thrangconfig = QtWidgets.QDialog()
    ui = Ui_ThrAngReconCfg()
    ui.setupUi(thrangconfig)
    thrangconfig.show()
    sys.exit(app.exec_())