# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'utils/etc/Qt_design/Tab4_vis_config.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

from PyQt5 import QtCore, QtGui, QtWidgets
import os
import glob


class Ui_ThrAngVisCfg (object):
    def setupUi (self, ThrAngThrAngVisconfig):
        ThrAngThrAngVisconfig.setObjectName("ThrAngThrAngVisconfig")
        # ThrAngThrAngVisconfig.resize(470, 260)
        ThrAngThrAngVisconfig.setGeometry(580, 360, 470, 280)  # setGeometry(x, y, w, h)
        
        self.groupBox = QtWidgets.QGroupBox(ThrAngThrAngVisconfig)
        self.groupBox.setGeometry(QtCore.QRect(10, 10, 450, 240))
        self.groupBox.setObjectName("groupBox")
        self.formLayout = QtWidgets.QFormLayout(self.groupBox)
        self.formLayout.setObjectName("formLayout")
        
        # ======= Title =======
        self.label_ttl = QtWidgets.QLabel(self.groupBox)
        self.label_ttl.setAutoFillBackground(True)
        self.label_ttl.setScaledContents(False)
        self.label_ttl.setAlignment(QtCore.Qt.AlignCenter)
        self.label_ttl.setWordWrap(False)
        self.label_ttl.setOpenExternalLinks(False)
        self.label_ttl.setObjectName("label_ttl")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.SpanningRole, self.label_ttl)
        
        # ======= (1) 3-angle DAT =======
        self.label_dat = QtWidgets.QLabel(self.groupBox)
        self.label_dat.setObjectName("label_dat")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_dat)
        
        self.comboBox_3angle = QtWidgets.QComboBox(self.groupBox)
        self.comboBox_3angle.setObjectName("comboBox_3angle")
        self.comboBox_3angle.setMinimumSize(120, 25)
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.comboBox_3angle)

        # - list of 3-angle DAT files -
        self.list_3ang_dat = next(os.walk('data/recon/3angle/OUTPUT/'))[1]
        self.comboBox_3angle.addItems(self.list_3ang_dat)
        self.comboBox_3angle.setCurrentIndex(0)
        
        # ======= (2) acquisition =======
        self.label_acq = QtWidgets.QLabel(self.groupBox)
        self.label_acq.setObjectName("label_acq")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_acq)
        
        self.comboBox_acq = QtWidgets.QComboBox(self.groupBox)
        self.comboBox_acq.setObjectName("comboBox_acq")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.comboBox_acq)
        
        self.list_acq = ['1','2','3']
        self.comboBox_acq.addItems(self.list_acq)
        self.comboBox_acq.setCurrentIndex(1)
        
        # ======= (3) iteration =======
        self.label_iter = QtWidgets.QLabel(self.groupBox)
        self.label_iter.setObjectName("label_iter")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_iter)
        
        self.spinBox_iter = QtWidgets.QSpinBox(self.groupBox)
        self.spinBox_iter.setSingleStep(1)
        self.spinBox_iter.setObjectName("spinBox_iter")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.spinBox_iter)
        
        # maxiters_onchanged
        self.maxiters_onchanged()  # onchanged of 3-angle dat
        self.comboBox_3angle.currentTextChanged.connect(self.maxiters_onchanged)
        self.comboBox_acq.currentTextChanged.connect(self.maxiters_onchanged)
        
        # ====== (4) Spacing ======
        self.label_sp = QtWidgets.QLabel(self.groupBox)
        self.label_sp.setObjectName("label_sp")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_sp)
        
        self.spinBox_sp = QtWidgets.QSpinBox(self.groupBox)
        self.spinBox_sp.setObjectName("spinBox_sp")
        self.spinBox_sp.setSingleStep(1)
        self.spinBox_sp.setMinimum(1)
        self.spinBox_sp.setMaximum(1000)
        self.spinBox_sp.setValue(256)
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.spinBox_sp)
        
        # ======= (5) axis  =======
        self.label_axis = QtWidgets.QLabel(self.groupBox)
        self.label_axis.setObjectName("label_axis")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.label_axis)
        
        self.comboBox_axis = QtWidgets.QComboBox(self.groupBox)
        self.comboBox_axis.setEditable(True)
        self.comboBox_axis.setPlaceholderText("")
        self.comboBox_axis.setObjectName("comboBox_axis")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.comboBox_axis)
        
        self.comboBox_axis.addItems(['X','Y','Z'])
        self.comboBox_axis.setCurrentIndex(0)
        
        # ======= (6) slice =======
        self.label_slice = QtWidgets.QLabel(self.groupBox)
        self.label_slice.setObjectName("label_slice")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.label_slice)
        
        self.horizSlider_slice = QtWidgets.QSlider(self.groupBox)
        self.horizSlider_slice.setOrientation(QtCore.Qt.Horizontal)
        self.horizSlider_slice.setObjectName("horizSlider_slice")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.horizSlider_slice)
        
        self.label_slice1 = QtWidgets.QLabel(self.groupBox)
        self.label_slice1.setObjectName("label_slice1")
        self.label_slice1.setAlignment(QtCore.Qt.AlignCenter)
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.SpanningRole, self.label_slice1)
        
        # --- onchange ---
        self.ax_onchanged()
        self.spinBox_sp.valueChanged.connect(self.ax_onchanged)
        self.comboBox_axis.currentTextChanged.connect(self.ax_onchanged)
        self.horizSlider_slice.valueChanged.connect(self.slider_onchanged)
        
        #  ======= Ok|cancel =======
        self.buttonBox = QtWidgets.QDialogButtonBox(self.groupBox)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setCenterButtons(True)
        self.buttonBox.setObjectName("buttonBox")
        self.formLayout.setWidget(8, QtWidgets.QFormLayout.SpanningRole, self.buttonBox)

        self.retranslateUi(ThrAngThrAngVisconfig)
        self.buttonBox.accepted.connect(ThrAngThrAngVisconfig.accept)  # type: ignore
        self.buttonBox.rejected.connect(ThrAngThrAngVisconfig.reject)  # type: ignore
        QtCore.QMetaObject.connectSlotsByName(ThrAngThrAngVisconfig)

    def retranslateUi (self, ThrAngThrAngVisconfig):
        _translate = QtCore.QCoreApplication.translate
        ThrAngThrAngVisconfig.setWindowTitle(_translate("ThrAngThrAngVisconfig", "3-angle vis config"))
        self.label_ttl.setText(_translate("ThrAngThrAngVisconfig", "Config of 3-angle visualization"))
        self.label_dat.setText(_translate("ThrAngVisconfig", "3-angle Dat"))
        self.label_acq.setText(_translate("ThrAngVisconfig", "Acquisition"))
        self.label_iter.setText(_translate("ThrAngVisconfig", "Iteration"))
        self.label_sp.setText(_translate("ThrAngVisconfig", "Spacing (mm)"))
        self.label_axis.setText(_translate("ThrAngVisconfig", "Axis"))
        self.label_slice.setText(_translate("ThrAngVisconfig", "Slice"))
        self.label_slice1.setText(_translate("ThrAngVisconfig", str(self.horizSlider_slice.value())))
    
    def maxiters_onchanged (self):
        self.acq = self.comboBox_acq.currentText()
        self.ThrAng_Aq_dir = f'data/recon/3angle/OUTPUT/{self.comboBox_3angle.currentText()}/Aq{self.acq}'
        self.list_3ang_aq = glob.glob(f'{self.ThrAng_Aq_dir}/ThreeAngleImage_aq{self.acq}_*.DAT')
        self.maxiters = len(self.list_3ang_aq)
        print(f'{self.comboBox_3angle.currentText()} list_3ang_aq({self.acq}): {len(self.list_3ang_aq)}')
        
        self.spinBox_iter.setValue(self.maxiters)
        self.spinBox_iter.setMaximum(self.maxiters)
        self.spinBox_iter.setMinimum(1) if self.maxiters > 0 else self.spinBox_iter.setMinimum(0)

    def ax_onchanged (self):
        self.axis  = self.comboBox_axis.currentText()
        self.nimgx = int(self.spinBox_sp.value() / 0.8)

        if  self.axis  == 'X':
            self.xlabel = 'Z'
            self.ylabel = 'Y'
            self.horizSlider_slice.setRange(1, self.nimgx)
            self.horizSlider_slice.setValue(self.nimgx // 2)
        elif self.axis == 'Y':
            self.xlabel = 'Z'
            self.ylabel = 'X'
            self.horizSlider_slice.setRange(1, self.nimgy)
            self.horizSlider_slice.setValue(self.nimgy // 2)
        elif self.axis == 'Z':
            self.xlabel = 'X'
            self.ylabel = 'Y'
            self.horizSlider_slice.setRange(1, self.nimgz)
            self.horizSlider_slice.setValue(self.nimgz // 2)
        
    def slider_onchanged(self):
        self.slice = self.horizSlider_slice.value()
        self.label_slice1.setText(str(self.slice))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    ThrAngVisconfig = QtWidgets.QDialog()
    ui = Ui_ThrAngVisCfg()
    ui.setupUi(ThrAngVisconfig)
    ThrAngVisconfig.show()
    sys.exit(app.exec_())